### ISSUE TITLE
Golem id issue

### ISSUE THREAD

**Issue by sor1n** [Draco18s/Artifacts#10]
http://pastebin.com/cFfx0j7n

Please fix your mod draco, I don't like people coming to me claiming this is caused by my mod when clearly this is on your side somehow :p I have no idea why this happens, because I looked at your code and things shouldn't conflict, but they clearly seem to for some reason.

**Comment by Draco18s** [comment]
The only way the conflict happens is when we BOTH use registerGlobalEntityID() and that somehow either between changing what mods are installed, or something else, both mods try to use ID 3.

https://github.com/sor1n/Jewelrycraft/blob/1.7.10/src/main/java/darkknight/jewelrycraft/entities/EntityList.java#L20-21

I haven't been maintaining the code here for a long, long time.  Yes, it needs to be fixed here.  But at least my mod gets an ID that is free and saves it to the config file, which the user can adjust if there's a problem.

Both of us should be using registerModEntity(), but as I said, I haven't been maintaining this code for a long while now.

**Comment by sor1n** [comment]
Alright. Well I will make sure to use just that for my next update so this conflict doesn't happen in the future.

**Comment by Tmtravlr** [comment]
I'd rather keep it as an ID that has a vanilla spawn egg (the registerGlobalEntityID() ), so that way it can be easily used in dispensers (perhaps for future traps?). 

There is only one mob in this mod, so if there is a confict, it's pretty easy to change the ID in the config file.

**Comment by sor1n** [comment]
Well lucky you >_> Yet again I am the one that has to change stuff it appears :/ this way people will at least crawl to you for conflicts :p I really am not in the mood to tell people to change the id in the proper config.

**Comment by Draco18s** [comment]
With 1.8, registerGlobalEntityID doesn't exist any more anyway.
