### ISSUE TITLE
Repair effect is too OP

### ISSUE THREAD

**Issue by iKurama** [Draco18s/Artifacts#14]
https://www.youtube.com/watch?v=evQO0eOp8nc

Mods:
Artifacts
Thermal Expansion.

**Comment by Draco18s** [comment]
This is a known issue with all items that claim to be "repairable" and aren't (because they're using the metadata for something else, like power).  This is not a bug with Artifacts, but rather (in this case) Thermal Expansion.

**Comment by iKurama** [comment]
Oka, Thx.
[Closing issue]

**Comment by Draco18s** [comment]
Best solution for the time being is to just not-abuse the effect.

**Comment by iKurama** [comment]
Yeah, I disabled any repair effect in configs. [Server side]
