### ISSUE TITLE
Excavation and Anti-Builder

### ISSUE THREAD

**Issue by Draco18s** [Draco18s/Artifacts#7]
Relevant code section:
https://github.com/Draco18s/Artifacts/blob/master/main/java/com/draco18s/artifacts/components/ComponentExcavation.java#L81-86

Reading a thread on the Modder Support forums made me realize that this artifact ability would bypass the anti-builder's protection zone.

Should add fire a BlockEvent.BreakEvent prior to destroying the block.

**Comment by Tmtravlr** [comment]
Actually it only fires if the "middle" block actually breaks, so it's not a problem. And even if you break one near the edge of the anti-builder zone, the anti-builder will replace it (like with explosions).

**Comment by Draco18s** [comment]
Cool.  It was something I wasn't sure about.
